# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BbXMIbr_93PkiBbUrKTNH1Bn40dpZ7ZB
"""

import pandas as pd
baza={
    "F.I.SH": ['Boltaboyev Tesha', 'Teshaboyev Bolta', 'Odilova Aziza','Azizov Ahmat','Ahamatov Mahmud','Mahmudov Eshmat','Akramova Madina' ],
    "Yoshi": ['16', '12', '18','18','13','18','17'],
    "Jinsi": ['o`g`il bola','o`g`il bola','qiz bola','o`g`il bola','o`g`il bola','o`g`il bola','qiz bola' ],
    "Maktab": [ '40','24','45','23','2','13','21'],
}
df=pd.DataFrame(baza)
print(df)

filtr=df[df['Jinsi']=='o`g`il bola']
print(filtr)

filtr=df[(df['Jinsi']=="o`g`il bola") & (df['Yoshi']>'15')]
print(filtr)

filtr=df[(df['Jinsi']=="o`g`il bola") & (df['Maktab']>'20')]
print(filtr)